spring:
  datasource:
    url: jdbc:mysql://localhost:3306/note?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=UTC
    username: bwkim
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
  datetime:
    scalars:
      date:
        scalarName: Date
      localDate:
        scalarName: LocalDate
      localDateTime:
        scalarName: LocalDateTime
      localTime:
        scalarName: LocalTime
      zone-conversion-enabled: true
